analyzer_rules:
    - unused_import
disabled_rules:
    - line_length
    - nesting
    - trailing_whitespace
    - vertical_whitespace_closing_braces
    - large_tuple
    - identifier_name
    - force_cast
    - file_length
opt_in_rules:
    - empty_string
    - file_name_no_space
    - force_unwrapping
    - file_types_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_parameters_brackets
    - sorted_imports
    - vertical_parameter_alignment_on_call
    - weak_delegate
    
excluded:
    - ${TARGETNAME}/Resource

identifier_name:
  excluded:
    - id
    - URL
